name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  autobahn-fuzzingclient:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2024-01-10
      - uses: Swatinem/rust-cache@v2
      - run: .scripts/autobahn-fuzzingclient.sh ci

  autobahn-fuzzingserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2024-01-10
      - uses: Swatinem/rust-cache@v2
      - run: .scripts/autobahn-fuzzingserver.sh ci

  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2024-01-10
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-fuzz
          use-tool-cache: true
      - run: .scripts/fuzz.sh

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly-2024-01-10
      - uses: Swatinem/rust-cache@v2
      - run: docker-compose -f .test-utils/docker-compose.yml up -d
      - run: sleep 30
      - run: .scripts/integration-tests.sh


  internal-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          profile: minimal
          toolchain: nightly-2024-01-10
      - uses: Swatinem/rust-cache@v2
      - run: .scripts/internal-tests.sh
